### ISSUE TITLE
Rename Repository?

### ISSUE THREAD

**Issue by jackpolifka** [TheSpearHero/carsonmcmahanportfolio.github.io#3]
What are your thoughts about renaming your repository from portfolio to carsonmcmahan.github.io? That will up date the URL to your portfolio so that it is carsonmcmahan.github.io versus carsonmcmahan.github.io/portfolio. That will remove the requirement of people having to remember the `portfolio` part if they try to remember the URL of your site.

**Comment by carsonmcmahan** [comment]
I will change it.
